taekwondokb/encyclopedia/urls.py
from django.urls import path
from . import views


app_name = 'encyclopedia'
urlpatterns = [
    path('', views.toms, name='volumes-list'),
    path('<slug:volume>/', views.volume, name='volume'),
    path('<slug:volume>/<int:page>/', views.page, name='page'),
]

taekwondokb/regulations/urls.py
from django.urls import path
from . import views


app_name = 'regulations'
urlpatterns = [
    path('', views.belts, name='belts-list'),
    path('<slug:belt_kup>/', views.regulation, name='regulation'),
]

taekwondokb/restapi/urls.py
from django.urls import path, include
from . import views


app_name = 'restapi'

urlpatterns = [
    path('',views.index, name='index'),
    path('docs/', views.docs, name='docs'),
    path('register/', views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', views.profile, name='profile'),
    path('token/', views.obtain_token, name='token'),


    path('api/v1/<uuid:token>/encyclopedia/', views.VolumesList.as_view(), name='api-volume-list'),
    path('api/v1/<uuid:token>/encyclopedia/<int:tom>/', views.VolumeDetail.as_view(), name='api-volume-detail'),
    path('api/v1/<uuid:token>/encyclopedia/<int:tom>/<int:page>', views.PageDetail.as_view(), name='api-page-detail'),

    path('api/v1/<uuid:token>/belts/', views.BeltList.as_view(), name='api-belt-list'),
    path('api/v1/<uuid:token>/belts/<slug:kupslug>', views.RegulationView.as_view(), name='api-regulation-view'),
]

taekwondokb/taekwondokb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('encyclopedia/', include('encyclopedia.urls')),
    path('regulations/', include('regulations.urls')),
    path('', include('restapi.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taekwondokb/regulations/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse

class Belt(models.Model):
    kup = models.CharField(max_length=30)
    kupslug = models.SlugField(primary_key=True, unique=True)
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to='regulations/belts')

    def __str__(self):
        return self.title + f"({self.kup})"
    
    def get_image(self):
        return self.image.url
    
    def get_absolute_url(self):
        return reverse('regulations:regulation', kwargs={'belt_kup': self.kupslug})
    

class Regulation(models.Model):
    belt = models.ForeignKey(Belt, on_delete=models.CASCADE)
    description = RichTextField()
    tul = RichTextField()
    kicks = RichTextField()
    sparings = RichTextField(null=True, blank=True)
    self_defence = RichTextField(null=True, blank=True)
    spec_tech = RichTextField(null=True, blank=True)
    power_kicks = RichTextField(null=True, blank=True)
    OFP = RichTextField()
    theory = RichTextField(null=True, blank=True)

    def __str__(self):
        return str(self.belt)
    
    def get_image(self):
        return self.belt.get_image()
    
    def get_absolute_url(self):
        return reverse('regulations:regulation', kwargs={'belt_kup': self.belt.kupslug})

taekwondokb/regulations/views.py
from django.shortcuts import render
from .models import Belt, Regulation

def belts(request):
    belts = Belt.objects.all()
    context = {
        'belts': belts,
        'title': 'Belts'
    }
    return render(request, 'belts.html', context)


def regulation(request, belt_kup):
    regulation = Regulation.objects.get(belt__kupslug = belt_kup)
    context = {
        'regulation': regulation,
        'title': regulation.belt.kup
    }
    return render(request, 'regulation.html', context)

taekwondokb/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link rel="icon" type="image/x-icon" href="{%static 'img/favicon.ico'%}">
    <title>Taekwondo ITF | {{title}}</title>
</head>
<body>


<section class="section">
    <nav class="level">
        <div class="level-item has-text-centered">
            <figure class="image is-64x64">
                <img src="{%static 'img/itf_logo.png'%}">
            </figure>
            <figure class="image is-64x64">
                <img src="{%static 'img/itf_ua_logo.png'%}">
            </figure>
        </div>

        <div class="level-item has-text-centered">
            <p class="title is-5">База знань Taekwon-do ITF України</p>
        </div>
        {%if request.path != '/'%}
        <div class="level-item has-text-centered">
            <a onClick="goBack()" class="button is-outlined is-rounded mx-4">
                <span class="icon">
                    <i class="fa-solid fa-chevron-left"></i>
                </span>
            </a>
            <a href="/" class="button is-outlined is-rounded mx-4">На головну</a>
        </div>
        {%endif%}
    </nav>
</section>
</section class="section is-medium" id="body-section">
    {%block content%}
    
    {%endblock%}
</section>

<footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Taekwondo ITF Knowledge base</strong> by <a href="https://github.com/AstralMortem">Vladyslav Chaliuk</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
        is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
    </div>
  </footer>



<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
<script src="https://unpkg.com/htmx.org@1.9.4"></script>
<script>
var btn = $('#button');
var btn2 =$("#button2")

$(window).scroll(function() {
  if ($(window).scrollTop() > 300) {
    btn.addClass('show');
    btn2.addClass('show')
  } else {
    btn.removeClass('show');
    btn2.removeClass('show')
  }
});

btn.on('click', function(e) {
  e.preventDefault();
  $('html, body').animate({scrollTop:0}, '300');
});


</script>

<script>
    function goBack(){
        var el = "{{request.path}}"
        let arr = el.split('/')
        if(arr[1] == 'encyclopedia'&& arr[2].startsWith('vol')){
            document.location.href = '/' + arr[1]
        }else if(arr[1] == 'regulations' && arr[2] !=""){
            document.location.href = '/' + arr[1]
        }
        else{
            document.location.href = '/'
        }
            
    }
</script>
<script>
    
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    
</script>

<script src="https://kit.fontawesome.com/9eabf3b90b.js" crossorigin="anonymous"></script>
</body>
</html>

taekwondokb/templates/belts.html
{%extends 'base.html'%}

{%block content%}

<div class="container">
    <div class="columns is-multiline has-text-centered">
        {%for belt in belts%}
            <div class="column is-4-desktop is-6-tablet is-12-mobile ">
                <a href="{{belt.get_absolute_url}}">
                <div class="card">
                    
                    <div class="card-content">
                        <figure class="image is-96x96 is-inline-block">
                            <img src="{{belt.get_image}}" alt="{{belt.title}}" width="128" height="64">
                        </figure>
                        <p class="title is-5">{{belt.kup}}</p>
                        <p class="subtitle is-5">{{belt.title}}</p>
                    </div>
                </div>
                </a>
            </div>
        {%endfor%}
    </div>
</div>

{%endblock%}

taekwondokb/templates/docs.html
{%extends 'base.html'%}

{%block content%}
    <div class="container ">
        <div class="columns is-multiline">
            <div class="column is-12">
                <p class="title is-5">Документація для розробників</p>
            </div>
            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">
                            1. Зареєструйтесь в системі
                        </p>
                    </header>
                    <div class="card-content">
                        <div class="columns is-centered">
                           
                            <div class="column is-2">
                                <a href="{%url 'restapi:register'%}" class="button is-outlined is-dark">Зареєструватися</a>
                            </div>
                            <div class="column is-2">
                                <a href="{%url 'restapi:login'%}" class="button is-dark">Увійти</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">
                            2. створіть API Key
                        </p>
                    </header>
                    <div class="card-content">
                        <p>Дайте назву ключа і система автоматично його згенерує</p>
                        <p>Ключ має стандарт uuid4, Наприклад: <span class="tag has-text-danger">16fd2706-8baf-433b-82eb-8c7fada847da</span></p>
                    </div>
                </div>
            </div>

            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">
                            3. Requests
                        </p>
                    </header>
                    <div class="card-content">
                        <p>Всі запити формуються в такому форматі</p>
                        <p><span class="tag">https://{{ request.META.HTTP_HOST }}/api/v1/<:token>/<:endpoints></span></p>
                        <p>Де token - це токен аутентифікації користувача, а endpoint лінк до данних</p>
                    </div>
                </div>
            </div>
            <div class="column is-12">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">
                            3. Endpoints
                        </p>
                    </header>
                    <div class="card-content">
                        <p class="title is-6"><span class="tag has-text-danger">/encyclopedia/</span> -- Список всіх томів</p>
                        <p class="title is-6"><span class="tag has-text-danger">/encyclopedia/<:tom>/</span> -- Зміст конкретного Тому.</p>
                        <p class="subtitle is-6"><span class="tag">:tom</span> - Номер Тому</p>
                        <p class="title is-6"><span class="tag has-text-danger">/encyclopedia/<:tom>/:page>/</span> -- Сторінка.</p>
                        <p class="subtitle is-6"><span class="tag">:tom</span> - Номер Тому</p>
                        <p class="subtitle is-6"><span class="tag">:page</span> - Номер сторінки</p>
                        <hr>
                        <p class="title is-6"><span class="tag has-text-danger">/belts/</span> -- Список всіх поясів</p>
                        <p class="title is-6"><span class="tag has-text-danger">/belts/<:kupslug></span> -- Нормативи на конкретний пояс</p>
                        <p class="subtitle is-6"><span class="tag">:kupslug</span> - ID поясу</p>
                        <hr>
                        <p class="title">Приклад:</p>
                        <p><span class="tag">https://{{ request.META.HTTP_HOST }}/api/v1/<:token>/belts/9-kup</span> -- Даний запит виведе нормативи на біло-жовтий пояс в форматі JSON</p>
                        <p>
                            <span class="tag has-text-danger">
                                <pre>
                                {{belt}}
                                </pre>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
    </div>
{%endblock%}

taekwondokb/templates/index.html
{%extends 'base.html'%}

{%block content%}
<div class="container">
<div class="columns is-centered is-multiline ">
    <div class="column is-4-desktop is-6-tablet is-10-mobile  is-offset-1-mobile">
        <a href="{%url 'encyclopedia:volumes-list'%}">
        <div class="card">
            <div class="card-content has-text-centered">
                <span class="icon is-large">
                    <i class="fa-solid fa-book fa-2xl"></i>
                </span>
                <p class="title is-5">Енциклопедія</p>
            </div>
        </div>
    </a>
    </div>
    <div class="column is-4-desktop is-6-tablet is-10-mobile  is-offset-1-mobile">
        <a href="{%url 'regulations:belts-list'%}">
        <div class="card">
            <div class="card-content has-text-centered">
                <span class="icon is-large">
                    <i class="fa-solid fa-hand-fist fa-2xl"></i>
                </span>
                <p class="title is-5">Атестації</p>
            </div>
        </div>
    </a>
    </div>
    <div class="column is-4-desktop is-6-tablet is-10-mobile  is-offset-1-mobile">
        <a href="{%url 'restapi:docs'%}">
        <div class="card">
            <div class="card-content has-text-centered">
                <span class="icon is-large">
                    <i class="fa-solid fa-globe fa-2xl"></i>
                </span>
                <p class="title is-5">API</p>
            </div>
        </div></a>
    </div>
</div>
</div>
{%endblock%}

taekwondokb/templates/page.html
{%extends 'base.html'%}

{%block content%}
{% load mathfilters %}

<div id="mySidenav" class="sidenav ">
    <a href="javascript:void(0)" class=" button is-rounded is-outlined closebtn mt-2" onclick="closeNav()">&times;</a>

    <p class="title is-5 has-text-white mx-4 my-2">Зміст</p>
    <div class="card mx-2">
        <div class="card-content" id="volume-content">
        </div>
    </div>
</div>

<div class="container" id="main">
    <a id="button"></a>
    <a id="button2" onclick="openNav()"></a>
    <div class="columns is-multiline">
        <div class="column is-12">
            <div class="card has-background-light ">
               
                <header class="card-header has-text-centered">
                     {%if page.title%}
                    <p class="card-header-title">
                        {{page.title}}
                    </p>
                     {%endif%}
                    <div class="card-header-icon">
                        
                        {%if page.page|sub:1 != 0%}
                        <a class="button is-rounded is-outlined is-dark mx-2" href="{%url 'encyclopedia:page' volume=page.tom.slug page=page.page|sub:1%}">
                            <span class="icon-text">
                                <span class="icon">
                                    <i class="fa-solid fa-chevron-left"></i>
                                </span>
                                <span>{{page.page|sub:1}}</span>
                            </span></a>
                        {%endif%}
                        {%if not page.is_last%}
                        <a class="button is-rounded is-outlined is-dark mx-2" href="{%url 'encyclopedia:page' volume=page.tom.slug page=page.page|add:1%}">
                            <span class="icon-text">
                                <span >{{page.page|add:1}}</span>
                                <span class="icon">
                                    <i class="fa-solid fa-chevron-right"></i>
                                </span>
                            </span></a>    
                        </a>
                        {%endif%}

                        
                        <button class="button is-rounded is-outlined is-dark" onclick="openNav()">Зміст</button>
                    </div>
                </header>
               
                <div class="card-content ">
                    <div class="content ">
                        {{page.text|safe}}
                    </div>
                </div>
                <footer class="card-footer ">
                    <p class="card-footer-item subtitle is-6">
                        Стр. {{page.page}}
                    </p>
                </footer>
            </div>
        </div>
    </div>
</div>

<script>

    function openNav() {
      document.getElementById("mySidenav").style.width = "400px";
      if(!$(".card-content").is("#new-volume-content")){
        htmx.ajax("GET","{%url 'encyclopedia:volume' volume=page.tom.slug%}", {target:"#volume-content", swap:"outerHTML"})
      }
      
      
      
    }
    
    /* Set the width of the side navigation to 0 */
    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
    }
</script>


{%endblock%}

taekwondokb/templates/register.html
{%extends 'base.html'%}

{%block content%}


<div class="container">
    <div class="card has-text-centered">
        <div class="card-content">
            <div class="columns is-multiline is-centered">
                <form class="form" action="{{request.path}}" method="post">
                    {%csrf_token%}
                    {% if form.errors %}
                    <div class="column is-12">
                        <p class="title has-text-danger">{{form.errors}}</p>
                    </div>
                    {% endif %}
                    <div class="column is-12">
                        <div class="field">
                            <label for="">Псевдонім</label>
                            <p class="control">
                                {{form.username}}
                            </p>
                        </div>
                    </div>
                    <div class="column is-12">
                        <div class="field">
                            <label for="">Email</label>
                            <p class="control">
                                {{form.email}}
                            </p>
                        </div>
                    </div>
                    <div class="column is-12">
                        <div class="field">
                            <label for="">Пароль</label>
                            <p class="control">
                                {{form.password1}}
                            </p>
                        </div>
                    </div>
                    <div class="column is-12">
                        <div class="field">
                            <label for="">Повторіть пароль</label>
                            <p class="control">
                                {{form.password2}}
                            </p>
                        </div>
                    </div>
                    <div class="column">
                        <button type="submit" class="button is-rounded is-dark">Створити</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
</div>

{%endblock%}

taekwondokb/templates/regulation.html
{%extends 'base.html'%}

{%block content%}


<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class=" button is-rounded is-outlined  closebtn mt-2" onclick="closeNav()">&times;</a>
        <div class="card mx-2">
            <div class="card-content is-flex is-flex-direction-column is-justify-content-space-around">
                {%if regulation.tul%}
                <a class="button is-rounded is-outlined mt-2 is-dark" href="#tul" onclick="closeNav()" >Тулі</a>
            {%endif%}
            {%if regulation.kicks%}
                    <a class="button is-rounded is-outlined mt-2 is-dark" href="#kicks" onclick="closeNav()">Удари</a>
            {%endif%}
            {%if regulation.sparings%}
                    <a class="button is-rounded is-outlined mt-2 is-dark" href="#sparing" onclick="closeNav()">Спаринг</a>
            {%endif%}
            {%if regulation.self_defence%}
                    <a class="button is-rounded is-outlined mt-2 is-dark" href="#self-defence" onclick="closeNav()">Самозахист</a>
            {%endif%}
            {%if regulation.spec_tech%}
                    <a class="button is-rounded is-outlined mt-2 is-dark" href="#spec-tech" onclick="closeNav()">Спец техніка</a>
            {%endif%}
            {%if regulation.power_kicks%}
                    <a class="button is-rounded is-outlined mt-2 is-dark"  href="#power-kick" onclick="closeNav()">Силові розбивання</a>
            {%endif%}
            {%if regulation.OFP%}
                    <a class="button is-rounded is-outlined mt-2 is-dark" href="#ofp" onclick="closeNav()">ЗФП</a>
            {%endif%}
            {%if regulation.theory%}
                    <a class="button is-rounded is-outlined mt-2 is-dark" href="#theory" onclick="closeNav()">Теорія</a>
            {%endif%}
            </div>
        </div>
            
</div>

<div class="container" id="main">
    <a id="button"></a>
    <a id="button2" onclick="openNav()"></a>
    <section class="section">
        <div class="columns is-multiline">
            <div class="column is-6">
                <div class="card">
                    <div class="card-content has-text-centered">
                        <img src="{{regulation.get_image}}">
                        <h1 class="title">{{regulation.belt.title}} ({{regulation.belt.kup}})</h1>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        {{regulation.description|safe}}
                    </div>
                </div>
                <div class="has-text-centered mt-5">
                    <button class="button is-rounded is-dark" onclick="openNav()">Навігатор</button>
                </div>   
            </div>
        </div>
    </section>
    <section class="section" id="tul">
        <div class="columns is-multiline">
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        <h1 class="title">Тулі</h1>
                        <div class="content">
                            {{regulation.tul|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {%if regulation.kicks%}
    <section class="section" id="kicks">
        <div class="columns is-multiline">
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        <h1 class="title">Удари</h1>
                        <div class="content">
                            {{regulation.kicks|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {%endif%}
    {%if regulation.sparings%}
    <section class="section" id="sparing">
        <div class="columns is-multiline">
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        <h1 class="title">Спаринги</h1>
                        <div class="content">
                            {{regulation.sparings|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {%endif%}
    {%if regulation.self_defence%}
    <section class="section" id="self_defence">
        <div class="columns is-multiline">
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        <h1 class="title">Самоозахист</h1>
                        <div class="content">
                            {{regulation.self_defence|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {%endif%}
    {%if regulation.spech_tech%}
    <section class="section" id="spec_tech">
        <div class="columns is-multiline">
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        <h1 class="title">Спец техніка</h1>
                        <div class="content">
                            {{regulation.spech_tech|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {%endif%}
    {%if regulation.power_kicks%}
    <section class="section" id="power_kick">
        <div class="columns is-multiline">
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        <h1 class="title">Силові розбивання</h1>
                        <div class="content">
                            {{regulation.power_kicks|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {%endif%}
    {%if regulation.OFP%}
    <section class="section" id="ofp">
        <div class="columns is-multiline">
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        <h1 class="title">Загальна фізична підготовка(ЗФП)</h1>
                        <div class="content">
                            {{regulation.OFP|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {%endif%}
    {%if regulation.theory%}
    <section class="section" id="theory">
        <div class="columns is-multiline">
            <div class="column">
                <div class="card">
                    <div class="card-content">
                        <h1 class="title">Теорія</h1>
                        <div class="content">
                            {{regulation.theory|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {%endif%}
</div>


<script>

function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

/* Set the width of the side navigation to 0 */
function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>

{%endblock%}

taekwondokb/templates/token.html
<form hx-post="{{request.path}}" method="post" class="form">
    {%csrf_token%}
    <div class="field">
        <label for="" class="label">{{form.name.label}}</label>
        <p class="control">
            {{form.name}}
        </p>
    </div>
    
    <button type="submit" class="button is-dark">Згенерувати</button>
</form>

taekwondokb/templates/tom.html
{%extends 'base.html'%}

{%block content%}


<div class="container">
    
    <div class="columns is-multiline">
        {%for vol in volume%}
            <div class="column is-3">
                
                <div class="card">
                    <a href="{%url 'encyclopedia:page' volume=vol.slug page=1%}">

                    <div class="card-content">
                        <h1 class="title is-3">Том № {{vol.tom}}</h1>
                        <p class="subtitle is-5">{{vol.title}}</p>
                        
                            <a href="{{vol.original_file.url}}" download class="button is-rounded is-dark mt-2">
                                <span class="icon">
                                    <i class="fa-solid fa-download"></i>
                                </span>
                            </a>
                        
                        
                    </div>
                </a>
                    <hr class="my-0">
                    <a hx-get="{%url 'encyclopedia:volume' volume=vol.slug%}" hx-swap="outerHTML" hx-target="#volume-content-{{vol.slug}}"  >
                    <header class="card-header card-header-menu">
                        <p class="card-header-title card-title">
                          Зміст
                        </p>
                        <button class="card-header-icon" aria-label="more options" >
                          <span class="icon">
                            <i class="fas fa-angle-down" aria-hidden="true"></i>
                          </span>
                        </button>
                    </header></a>
                    <div id="volume-content-{{vol.slug}}">
                    </div>
                </div>
            </div>
            
        {%endfor%}
    </div>
</div>



{%endblock%}

<script>
    var el = $('.card-header');
    el.click(function(el){
        alert("dfsf");
    })
</script>

taekwondokb/templates/volume-detail.html
<div class="card-content" id="new-volume-content">
    <div class="content is-flex is-flex-direction-column">
        {%for page in pages %}
            {%if page.title%}<a href="{{page.get_absolute_url}}">Стр.{{page.page}} - {{page.title}}</a>{%endif%}
        {%endfor%}
    </div>
</div>